### ISSUE TITLE
Command Line - Specify Partitions and Directories

### ISSUE THREAD

**Issue by lukasbradley** [hellonarrativ/spectrify#54]
Colin, Apologies if this is the wrong place.  I didn't want to bombard you on LinkedIn.  ;)  

I wanted to make sure this feature was NOT available before I gave a presentation:

From the command line, is it possible to specify which partitions to use and how the folder structure should be allocated?  I'm GUESSING you're introspecting the table to export itself and using those keys to determine partitions.

The question behind the question is to allow for directory structures that mimic the nomenclature used by Redshift Spectrum as specified here:  https://docs.aws.amazon.com/redshift/latest/dg/c-spectrum-external-tables.html

The end goal would be to (possibly) use Glue to auto-discover these directory structures as well as use Redshift Spectrum to have them explicitly defined.

**Comment by c-nichols** [comment]
Right now Spectrify does not have built-in support for exporting partitioned data.  Partly, this is because (afaik) Redshift doesn't let you specify a partitioning scheme during UNLOAD... if you want partitioned data in CSVs, you have to make a number of UNLOAD queries yourself.

It's pretty easy to do partitioning w/ Spectrify, but it does require coding.  You can see this in action here: https://github.com/hellonarrativ/spectrify/blob/master/examples/weekly_partitions.py
